version: '3'
services:
  postgresdb:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: cash_flow
      POSTGRES_PASSWORD: cash_flow
      POSTGRES_DB: cash_flow
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - cashflow
    healthcheck:
      test: [
        "CMD",
        "pg_isready",
        "-h", "localhost",
        "-U", "cash_flow",
        "-d", "cash_flow"
      ]
      interval: 2s
      timeout: 60s
      retries: 30

  app:
    build:
      context: ../
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    networks:
      - cashflow
    depends_on:
      postgresdb:
        condition: service_healthy
    environment:
      - POSTGRES_URL=jdbc:postgresql://postgresdb:5432/cash_flow

networks:
  cashflow:
    driver: bridge